### ISSUE TITLE
Make RabbitMQ available in the infrastructure for use in the transactional flow

### ISSUE THREAD

**Issue by gitfelipegomes** [LerianStudio/midaz#194]

**Comment by MartinezAvellan** [comment]
![Image](https://github.com/user-attachments/assets/585d3dc7-6c55-4759-a126-ac013596046e)

**Comment by MartinezAvellan** [comment]
![Image](https://github.com/user-attachments/assets/2008c016-6130-4925-861f-44012ef0d34f)

**Comment by MartinezAvellan** [comment]
![Image](https://github.com/user-attachments/assets/919b9879-311e-414e-b336-724f7dd06f3c)

**Comment by MartinezAvellan** [comment]
![Image](https://github.com/user-attachments/assets/d52da39d-cf68-4aeb-8bf7-f981d5e82200)

**Comment by MartinezAvellan** [comment]
![Image](https://github.com/user-attachments/assets/b6ef2537-dc39-4b4c-b366-318f3ef34dea)
