### ISSUE TITLE
Creation of sequence diagrams for transaction flows.

### ISSUE THREAD

**Issue by gitfelipegomes** [LerianStudio/midaz#233]
## Context

Create sequence diagrams for transaction flow use cases:

- Flat Transaction (Auto Commit)
- Pre-transaction
- Commit Transaction
- Cancel Transaction
- Revert Transaction

**UPDATED**
[transactions.zip](https://github.com/user-attachments/files/17751622/transactions.zip)

**Comment by MartinezAvellan** [comment]
**FLAT TRANSACTION**

![Image](https://github.com/user-attachments/assets/a14d94c2-f5bf-4320-ac92-c498577c6e8b)

**Comment by MartinezAvellan** [comment]
**PRE TRANSACTION**

![Image](https://github.com/user-attachments/assets/bf3aec3c-5a47-4d78-86d7-95e4863a9825)

**Comment by MartinezAvellan** [comment]
**COMMIT TRANSACTION**

![Image](https://github.com/user-attachments/assets/7bad333b-d221-4ecc-8cfb-453800a0f936)

![Image](https://github.com/user-attachments/assets/39a50a6c-91d2-4bad-9c1c-c8c005075cb8)

**Comment by MartinezAvellan** [comment]
**REVERT TRANSACTION**

![Image](https://github.com/user-attachments/assets/a800953d-ac35-4c04-87be-6c8c52cb084e)


![Image](https://github.com/user-attachments/assets/3ce3c7ea-0a9c-4980-bd83-b3eca6bce6e2)

**Comment by MartinezAvellan** [comment]
**CANCEL TRANSACTION**

![Image](https://github.com/user-attachments/assets/5280cfd8-561b-4ba1-bae8-4a739ac6a56a)


![Image](https://github.com/user-attachments/assets/7c25306c-55fc-40a0-9d38-697f80518e3f)

**Comment by gitfelipegomes** [comment]
> **PRE TRANSACTION**
> 
> ![Image](https://github.com/user-attachments/assets/238666fd-ef74-4364-9596-0bb111c95eaf)
> 
> ![Image](https://github.com/user-attachments/assets/a7117580-4736-4ec4-a9ec-d06ac165a01a)

In the pre-transaction flow, I still think we need to extend the validation before returning to the user.

Considering a flow where the transaction is “validated” to ensure that the accounts have sufficient balance and the values are temporarily placed in `on_hold`, the transaction status would be `PRE_APPROVED`, awaiting either the `commit` or `canceled` action.

make sense?

Contributions here @fredcamaral @jeffersonrodrigues92 ?

**Comment by MartinezAvellan** [comment]
> [@MartinezAvellan](https://github.com/MartinezAvellan) In my view, it would be a status flow in the model below.

I agree.

**Comment by MartinezAvellan** [comment]
**NEW PRE TRANSACTION**

![Image](https://github.com/user-attachments/assets/81ca3263-4df3-478a-b549-fe47455b4446)


![Image](https://github.com/user-attachments/assets/e04b8e1a-f8a2-4944-9180-3ec659cb2041)


Done @gitfelipegomes
