### ISSUE TITLE
Change external account type rules in Account context

### ISSUE THREAD

**Issue by gitfelipegomes** [LerianStudio/midaz#334]
### Context

Accounts of the `external` type are control accounts designed to ensure Midaz’s traceability with the external world. Therefore, these accounts should not be modified by the user during operation, as doing so may cause issues with flows and reconciliation.

We need to implement some rules to prevent modifications.

### How to do it

1. Do not allow the deletion of accounts of type `external`
2. Do not allow modifications to accounts of type `external`
3. Do not allow accounts with aliases starting with `@external/`

**Comment by qnen** [comment]
I'm currently waiting for this task to be completed before I can proceed: [Issue](https://github.com/LerianStudio/midaz-technical-writing/issues/16).
